---
- hosts: localhost
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - unzip
          - wget
          - go
        state: present
        update_cache: yes

    
